parameters:
#    manager_api.example.class: Manager\ApiBundle\Example

services:
#    manager_api.example:
#        class: %manager_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]