manager_charge:
    resource: "@ManagerChargeBundle/Controller/"
    type:     annotation
    prefix:   /charge

techlog_manager:
    resource: "@ManagerTechlogBundle/Controller/"
    type:     annotation
    prefix:   /techlog_manager

manager_api:
    resource: "@ManagerApiBundle/Controller/"
    type: annotation
    prefix:   /api

manager_user:
    resource: "@ManagerUserBundle/Controller/"
    type:     annotation
    prefix:   /user

admin_root:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /user/homepage
        permanent: true
